nginx:
  image: nginx
  ports:
    - 80:80
  volumes:
    - /tmp/nginx:/etc/nginx/conf.d

nginxgen:
  image: jwilder/docker-gen:0.3.4
  volumes:
    - /tmp/nginx:/etc/nginx/conf.d
    - /var/run/docker.sock:/tmp/docker.sock
    - ./templates:/etc/docker-gen/templates
  command: -notify-sighup dockerconf_nginx_1 -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
  links:
    - nginx
    - app

mongo:
  image: mongo:3.0
  restart: always
  mem_limit: 100m

app:
  image: splinecl/developer-day 
  links:
    - mongo:db
  environment:
    - PROXY_GROUP=devday

